# Generated by Django 3.0 on 2019-12-22 12:49

from django.db import migrations, models

import users.managers


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20191221_2011'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
