# Generated by Django 3.0 on 2020-01-25 12:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20191222_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('confirmed', 'user verified'), ('unconfirmed', 'user dont verified')],
                                   default='unconfirmed', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 25, 12, 55, 25, 690642)),
        ),
    ]
