# Generated by Django 3.0 on 2020-02-03 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_auto_20200128_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='User birth date',
                                   verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='User email', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='User first name', max_length=254, null=True,
                                   verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='User last login date', null=True,
                                       verbose_name='Last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='User last name', max_length=254, null=True,
                                   verbose_name='Last name'),
        ),
    ]
