# Generated by Django 3.0 on 2020-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0002_auto_20191224_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(
                choices=[('WAITING_CONFIRMATION', 'waiting_confirmation'), ('PUBLISHED', 'published'),
                         ('UNPUBLISHED', 'unpublished')], default='WAITING_CONFIRMATION', max_length=20),
        ),
    ]
