# Generated by Django 3.0 on 2020-02-03 18:26

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_auto_20200203_1826'),
        ('news', '0004_auto_20200123_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': [('publish', 'can_publish_without_moderation')], 'verbose_name': 'news',
                     'verbose_name_plural': 'news'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(default=68, help_text='Link to news', on_delete=django.db.models.deletion.CASCADE,
                                    to='news.News', verbose_name='News'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='Link to author', on_delete=django.db.models.deletion.CASCADE,
                                    to='users.User', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of posted', verbose_name='Posted date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Comment text', max_length=100, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(help_text='Link to author', on_delete=django.db.models.deletion.CASCADE,
                                    to='users.User', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Insert your news here', verbose_name='News content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of posted', verbose_name='Posted date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('unpublished', 'unpublished'), ('published', 'published'),
                                            ('waiting_confirmation', 'waiting_confirmation')],
                                   default='waiting_confirmation', help_text='This is status of news publication',
                                   max_length=20, verbose_name='Confirmation status'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Use short roomy title', max_length=30, verbose_name='Title'),
        ),
    ]
